### ISSUE TITLE
Stamina fix is not working

### ISSUE THREAD

**Issue by Dorosz63** [BGforgeNet/EItweaks#1]
_"When a player character is running, stamina is depleted by points rather than percentage, which allows to run longer as stamina grows."_

Hi, when I was testing this mod I have noticed that the "run longer" fix does not work even after replacing game.exe in the main game folder. The character's running distance is the same, no matter if it has 50 or 200 stamina points. I hex-compared it to _Engine\game.exe_ from EItweaks folder and they are identical (but it is indeed slightly different from the file from the main game directory).

Tested with:
- English GOG version of Evil Islands
- EItweaks 1.046.0 (which includes the newest Addon library v0.11.0.0)

The rest of the tweaks work fine so far.

**Comment by Dorosz63** [comment]
I have found a good argument that if we want to improve running, we should consider all parameters (stamina, dexterity, endurance, recovery, etc.) to prevent imbalances. Now, I am not sure if there is reasonable fix for it, which will not involve total re-balancing of skills only for such a minor thing as running. Maybe it should be left the way it is? (percentage instead of stamina)

**Comment by burner1024** [comment]
How did you test? Share saves for comparison? Or maybe a video?

I really tested on Russian version only (I hate Zak's screeching voice in English localization). And the mod itself is based on RU v1.07 patch, which isn't available for other languages.

About the rest:
1. If you want to leave it alone, then just don't replace the exe.
2. Running may be a minor skill when savescumming, but when playing [Hardcore/Ironman](https://pihwiki.bgforge.net/Hardcore_Glossary#Hardcore), it's most essential.
3. I thought about implementing a more sophisticated formula, although not based on skills/stats, but rather encumbrance.
    Instead of doing hard switch from run to walk when overloaded, I'd rather see both run speed and stamina depletion proportional to current encumbrance (in %). That would tie together stats, protection and mobility for the player to balance.
    That's just an idea at this point, though, and it's not so easy to implement.

**Comment by burner1024** [comment]
no response

**Comment by Dorosz63** [comment]
Example: If Zak has 50 stamina and he is running through Hunter campsite, his stamina is reduced to 0. If Zak has 200 stamina and he is doing the same thing, on the exact same distance, his stamina is also reduced to 0. I believe that intention of this modification was to be able to run on longer distances once stamina is increased, which is not happening, at least on English GOG version (other tweaks are working fine).

![6684-7-evil-islands-curse-of-the](https://user-images.githubusercontent.com/27143836/127462015-1751b088-a834-4e94-adef-0f20c866ca51.jpg)

**Comment by burner1024** [comment]
saves?

**Comment by Dorosz63** [comment]
In the afternoon, I do not have a computer with Evil Islands with me. I will edit this post.

**Comment by Dorosz63** [comment]
I am sorry, I have busy days in work. I still have this on my to-do list, but it will take some time before I will be able to check this.
